spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: aray
    password: aray
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa:
  #   generate-ddl: true
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: "/"
